### ISSUE TITLE
V0.2.6 on CC2652P7

### ISSUE THREAD

**Issue by NightHawkATL** [mercenaruss/uzg-firmware#36]
I have finally updated to the "latest" version and I am still seeing daily disconnects with my Home Assistant setup.

I have tried:
- Rebooting the ESP32 module
- Rebooting the Zigbee module
- Cycling the port on the switch it is connected to
- Reloading the integration
- Rebooting Home Assistant

Is there anything that can be done to make this more stable or should I just move to a competitor device? This has only happened in the last month or so and was rock solid before that.

**Comment by xpenno255** [comment]
I'm also having issues that sounds similar to this. For me it happens every 2 to 3 days.

I'm using ZHA in Home Assistant OS 2024.04.2 I was previously running Skyconnect via USB but I migrated to UZG-01 in ethernet mode and updated directly to v0.2.6.

At the time the following error appears in home assistant.

`Logger: zigpy.application
Source: /usr/local/lib/python3.12/site-packages/zigpy/application.py:675
First occurred: 20:24:14 (1 occurrences)
Last logged: 20:24:14

Watchdog failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zigpy_znp/api.py", line 1059, in request
    response = await response_future
               ^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 673, in _watchdog_loop
    await self.watchdog_feed()
  File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 655, in watchdog_feed
    await self._watchdog_feed()
  File "/usr/local/lib/python3.12/site-packages/zigpy_znp/zigbee/application.py", line 628, in _watchdog_feed
    await self._znp.request(c.SYS.Ping.Req())
  File "/usr/local/lib/python3.12/site-packages/zigpy_znp/api.py", line 1055, in request
    async with async_timeout.timeout(
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError`

**Comment by NightHawkATL** [comment]
@xpenno255 i just recently added the MQTT server connection to add functions to monitor it in HA. I have an automation that watches the state of ZHA and if it goes to unavailable or unresponsive, it sends a message and then triggered the zigbee reboot of the UZG-01. Once it comes back up, it sends another message letting me know it may be working again.

Trying this for a minute to see if it helps.

**Comment by tavalin** [comment]
Can you share your automation or a link to it please? I'm having similar issue

**Comment by NightHawkATL** [comment]
@tavalin ![Uploading Screenshot_20240410-185353_Home Assistant.png …]()

**Comment by NightHawkATL** [comment]
> Can you share your automation or a link to it please? I'm having similar issue 

```
alias: "Notify: Zigbee Control Down"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.texas_instruments_coordinator
    from: null
    to: unavailable
condition:
  - type: is_not_connected
    condition: device
    device_id: aeb436d05cd0bbf44cac48c2043ce89c
    entity_id: de5d3f881a20242a52e9f54da7b74635
    domain: binary_sensor
action:
  - service: notify.mobile_iphone_13
    metadata: {}
    data:
      message: >-
        The Zigbee coordinator has gone unresponsive. The zigbee radio has been
        restarted and should become responsive shortly.
      title: Notice!
  - device_id: aeb436d05cd0bbf44cac48c2043ce89c
    domain: button
    entity_id: 3affbf71bed59a894f70b0c1c110753b
    type: press
mode: single

```
